name: E2E

on:
    push:
        branches:
            - "main"
            - "ci-*"
    pull_request:
        branches: ["main"]

env:
    CARGO_TERM_COLOR: always

jobs:
    e2e:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout source code
              uses: actions/checkout@v3
            - name: Build
              run: |
                  cargo build --release
                  cargo build --package=whipinto --release
                  cargo build --package=whepfrom --release

            - name: Install Tools
              run: |
                  sudo apt update -y &&  sudo apt install ffmpeg  &&  sudo apt install python3-pip
                  pip3 install opencv-python && pip3 install Pillow
            - name: Install vmaf
              run: |
                  sudo apt install docker
                  wget https://github.com/Netflix/vmaf/archive/refs/tags/v2.3.0.tar.gz
                  tar -zxvf v2.3.0.tar.gz
                  cd ./vmaf-2.3.0
                  docker build -t vmaf .
            - name: Run E2E Test
              run: |
                  sudo ./test.sh


