name: E2E

on:
    push:
        branches:
            - "main"
            - "ci-*"
    pull_request:
        branches: ["main"]

env:
    CARGO_TERM_COLOR: always

jobs:
    e2e:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout source code
              uses: actions/checkout@v3
            - name: Build
              run: |
                  cargo build --release
                  cargo build --package=whipinto --release
                  cargo build --package=whepfrom --release

            - name: Install Tools
              run: |
                  sudo apt update -y && sudo apt install ffmpeg && sudo apt install docker
                  wget https://raw.githubusercontent.com/fastfeee/live777/ci-e2e/multirun_test.sh
                  chmod +x multirun.sh
                  git clone https://github.com/Netflix/vmaf.git
                  cd vmaf
                  docker build -t vmaf .

            - name: Run E2E Test
              run: ./e2e.sh
